name: daily_tracker
description: A new Flutter project for Daily Expense Tracking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  # 🌟 FIX 1: sqflite အစား လုံခြုံရေးအတွက် sqflite_sqlcipher ကို ပြောင်းသုံးထားသည်
  sqflite_sqlcipher: ^3.0.3 
  path_provider: ^2.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  math_expressions: ^2.4.0
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # 🌟 FIX 2: App Icon ပြောင်းရန်အတွက် ထည့်သွင်းထားသည်
  flutter_launcher_icons: ^0.13.1

# 🌟 FIX 3: App Icon အတွက် လမ်းကြောင်း ညွှန်ပေးခြင်း
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  
