name: Manual Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean Workspace & Build APK
        run: |
          flutter create app_workspace --org com.tkr --project-name daily_tracker
          cp -r lib/* app_workspace/lib/
          cp pubspec.yaml app_workspace/
          cd app_workspace
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Get SHA1 Fingerprint
        run: |
          echo "==== ဤနေရာရှိ လက်ဗွေရာကို ကူးယူပါ ===="
          keytool -printcert -jarfile app_workspace/build/app/outputs/flutter-apk/app-release.apk | grep SHA1
          echo "======================================"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DailyTracker-Draft-APK
          path: app_workspace/build/app/outputs/flutter-apk/app-release.apk
          
